!
! Copyright (C) 2012 Quantum ESPRESSO group
! This file is distributed under the terms of the
! GNU General Public License. See the file `License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!
SUBROUTINE write_modes_out( irr, imode0 )
  !
  !! This routine writes the displacements on the representation \(\text{irr}\)
  !! that starts at mode \(\text{imode0}\).
  !
  USE kinds, ONLY : DP
  USE ions_base, ONLY : nat
  USE modes, ONLY : u, npert
  USE io_global, ONLY : stdout
  !
  IMPLICIT NONE
  !
  INTEGER, INTENT(IN) :: imode0
  !! starting mode
  INTEGER, INTENT(IN) :: irr
  !! representation index
  !
  ! ... local variables
  !
  INTEGER :: mu, nu
  
  WRITE( stdout, '(5x,"Irreps are as follows:",/)')
  IF (npert (irr) .eq.1) THEN
     WRITE( stdout, '(20x," mode #",i4)') imode0 + 1
     WRITE( stdout, '(20x," (",2f10.5,"   ) ")')  ( (u (mu, nu) ,&
          &nu = imode0 + 1, imode0 + npert (irr) ) , mu = 1, 3 * nat)
  ELSEIF (npert (irr) .eq.2) THEN
     WRITE( stdout, '(2(10x," mode #",i4,16x))') imode0 + 1, &
          imode0 + 2
     WRITE( stdout, '(2(10x," (",2f10.5,"   ) "))')  ( (u (mu, nu) , nu &
          &= imode0 + 1, imode0 + npert (irr) ) , mu = 1, 3 * nat)
  ELSEIF (npert (irr) .eq.3) THEN
     WRITE( stdout, '(4x,3(" mode #",i4,13x))') imode0 + 1, imode0 &
          + 2, imode0 + 3
     WRITE( stdout, '((5x,3("(",2f10.5," ) ")))') ( (u (mu, nu) , &
          nu = imode0 + 1, imode0 + npert (irr) ) , mu = 1, 3 * nat)
  ELSE
     WRITE( stdout, '(4x,4(" mode #",i4,13x))') imode0 + 1, imode0 &
          + 2, imode0 + 4
     WRITE( stdout, '((5x,4("(",2f10.5," ) ")))') ( (u (mu, nu) , &
          nu = imode0 + 1, imode0 + npert (irr) ) , mu = 1, 3 * nat)
  ENDIF
  
  RETURN
END SUBROUTINE write_modes_out

SUBROUTINE write_pattern_basis_out( filpattern )
  !
  !! Writes the displacement pattern basis used by ph.x.
  !! Each column of \(u\) is one pattern, expressed in the Cartesian
  !! atomic-displacement basis \((na,ipol)\).
  !
  USE kinds, ONLY : DP
  USE ions_base, ONLY : nat
  USE io_global, ONLY : ionode, stdout
  USE modes, ONLY : nirr, npert, u
  USE control_ph, ONLY : current_iq, ldisp, qplot
  !
  IMPLICIT NONE
  !
  CHARACTER(LEN=*), INTENT(IN) :: filpattern
  !! requested output file name
  !
  INTEGER :: iunit, irr, ipert, imode0, imode, na, ipol, mu
  INTEGER, EXTERNAL :: find_free_unit
  CHARACTER(LEN=6), EXTERNAL :: int_to_char
  CHARACTER(LEN=256) :: filename
  !
  IF (.NOT. ionode) RETURN
  !
  filename = TRIM(filpattern)
  IF (ldisp .OR. qplot) filename = TRIM(filename) // '.q_' // &
                                  TRIM(int_to_char(current_iq))
  !
  iunit = find_free_unit()
  OPEN (UNIT = iunit, FILE = TRIM(filename), STATUS = 'unknown', &
        FORM = 'formatted')
  !
  WRITE(iunit,'("# Pattern basis generated by ph.x")')
  WRITE(iunit,'("# Columns are displacement patterns in Cartesian atomic-displacement coordinates.")')
  WRITE(iunit,'("# Patterns are constructed by diagonalizing the little-group symmetrized random matrix.")')
  WRITE(iunit,'("# Symmetry operations are applied internally in crystal coordinates; the stored u columns are Cartesian.")')
  WRITE(iunit,'("# For each pattern: atom_index  cartesian_index  real(u)  imag(u)")')
  WRITE(iunit,'("# current_iq = ",i8)') current_iq
  WRITE(iunit,'("# nat       = ",i8)') nat
  WRITE(iunit,'("# nirr      = ",i8)') nirr
  WRITE(iunit,'("# npert:")')
  WRITE(iunit,'(10i8)') (npert(irr), irr = 1, nirr)
  !
  imode0 = 0
  DO irr = 1, nirr
     WRITE(iunit,'(/,"# irrep ",i8," npert ",i8)') irr, npert(irr)
     DO ipert = 1, npert(irr)
        imode = imode0 + ipert
        WRITE(iunit,'("# pattern ",i8," irrep ",i8," ipert ",i8)') &
             imode, irr, ipert
        DO na = 1, nat
           DO ipol = 1, 3
              mu = 3 * (na - 1) + ipol
              WRITE(iunit,'(2i8,2es24.16)') na, ipol, DBLE(u(mu, imode)), &
                   AIMAG(u(mu, imode))
           END DO
        END DO
     END DO
     imode0 = imode0 + npert(irr)
  END DO
  !
  CLOSE(iunit)
  WRITE(stdout,'(5x,"Pattern basis written to file ",a)') TRIM(filename)
  !
  RETURN
END SUBROUTINE write_pattern_basis_out

SUBROUTINE write_dyn_pattern_basis_out( fildynpattern )
  !
  !! Writes the dynamical matrix as represented in the pattern basis.
  !
  USE kinds, ONLY : DP
  USE ions_base, ONLY : nat
  USE io_global, ONLY : ionode, stdout
  USE dynmat, ONLY : dyn
  USE modes, ONLY : u, nirr, npert
  USE control_ph, ONLY : current_iq, ldisp, qplot
  !
  IMPLICIT NONE
  !
  CHARACTER(LEN=*), INTENT(IN) :: fildynpattern
  !! requested output file name
  COMPLEX(DP), ALLOCATABLE :: dyn_pattern(:, :)
  !! dynamical matrix projected in the pattern basis
  !
  INTEGER :: iunit, ierr, irr, jrr, imode0, jmode0, ipert, jpert, mu, nu
  INTEGER, EXTERNAL :: find_free_unit
  CHARACTER(LEN=6), EXTERNAL :: int_to_char
  CHARACTER(LEN=256) :: filename
  !
  IF (.NOT. ionode) RETURN
  !
  ALLOCATE(dyn_pattern(3*nat, 3*nat), STAT=ierr)
  IF (ierr /= 0) CALL errore('write_dyn_pattern_basis_out', &
       'allocating dyn_pattern', ierr)
  dyn_pattern = (0.d0, 0.d0)
  CALL rotate_pattern_add(nat, u, dyn_pattern, dyn)
  !
  filename = TRIM(fildynpattern)
  IF (ldisp .OR. qplot) filename = TRIM(filename) // '.q_' // &
                                  TRIM(int_to_char(current_iq))
  !
  iunit = find_free_unit()
  OPEN (UNIT = iunit, FILE = TRIM(filename), STATUS = 'unknown', &
        FORM = 'formatted', IOSTAT=ierr)
  IF (ierr /= 0) THEN
     DEALLOCATE(dyn_pattern)
     CALL errore('write_dyn_pattern_basis_out', &
          'opening output file '//TRIM(filename), ierr)
  END IF
  !
  WRITE(iunit,'("# Dynamical matrix generated by ph.x in the pattern basis")')
  WRITE(iunit,'("# The Cartesian dynamical matrix is final-symmetrized, then projected as U^dagger D U.")')
  WRITE(iunit,'("# Matrix elements are indexed by pattern number.")')
  WRITE(iunit,'("# For each element: row_pattern  col_pattern  real(dyn)  imag(dyn)")')
  WRITE(iunit,'("# current_iq = ",i8)') current_iq
  WRITE(iunit,'("# nat       = ",i8)') nat
  WRITE(iunit,'("# nirr      = ",i8)') nirr
  WRITE(iunit,'("# npert:")')
  WRITE(iunit,'(10i8)') (npert(irr), irr = 1, nirr)
  !
  imode0 = 0
  DO irr = 1, nirr
     jmode0 = 0
     DO jrr = 1, nirr
        WRITE(iunit,'(/,"# block row_irrep ",i8," col_irrep ",i8)') irr, jrr
        DO ipert = 1, npert(irr)
           mu = imode0 + ipert
           DO jpert = 1, npert(jrr)
              nu = jmode0 + jpert
              WRITE(iunit,'(2i8,2es24.16)') mu, nu, DBLE(dyn_pattern(mu, nu)), &
                   AIMAG(dyn_pattern(mu, nu))
           END DO
        END DO
        jmode0 = jmode0 + npert(jrr)
     END DO
     imode0 = imode0 + npert(irr)
  END DO
  !
  CLOSE(iunit)
  DEALLOCATE(dyn_pattern)
  WRITE(stdout,'(5x,"Pattern-basis dynamical matrix written to file ",a)') &
       TRIM(filename)
  !
  RETURN
END SUBROUTINE write_dyn_pattern_basis_out